language: ruby
sudo: false
services:
  - postgresql
  - redis
addons:
  postgresql: '9.6'
before_script:
  - bundle exec rake db:test:prepare
cache: bundler
notifications:
  email: false
  slack:
    secure: RVF9kM2YPIpJgLk33frHD82KhC7Vl8gXytlARpwpYwtsPJXZQngYHpdWk4rEZIP7MiSj0fFxO6icY8S2eWXRftyf8rWZVY4hENHt6afyE+mYuVnEdvjDaprS/2sBUlU+lz//23mtME0jR2EC+TuJYL4f8LaZ4+2UGSDlUZKu4Q00YhNUubfc2sTkLWfRaSzHMcsl2iZs4H7JzOOLr4+mUEl1Ybzv+3LtqQ2ePODDsdytBcT6o7ILAX0PZz6495lhAVus2G4NNSDGYax4rFSjviLOpFGLQLQgCd30IBWj1Bll+dNCjjW1HVq+h3XHt4DQt3GeswYLLxNn5OMICc7B+Ao0uSfbU3sqRsMvK/Pfwe33YwgYJ6OzMVK35+91u8ZZcSJTqjsy7teLGmor8hqC2w821gB68JqAxDPg7+8zZBYPnqnRCoqNuu33ymY0ya1QQ08dBlnVqMQV7guB+9mad6GQmaPodhVCfVgvP4Stqtvh8yhrkLLiZ+PlE0LjmIFpXFmf3sK1zuzi0VFpZcGqXkCSrRNs8e5W/7UIYgv83iGCewXqxqTPTNpehtrb3p2n91gtQTKpMJJi2Rc3xFLP9jYetS/E1s6BB+vYbHPZzeE0oJUY2ff0zew16JL5sDQebswgwhmaVk9h7GC1DLkivUHuS/VjC+jY7Oa20xyAedE=
