language: ruby
sudo: false
services:
- redis
before_script:
- bundle exec rake db:test:prepare
cache: bundler
notifications:
  email: false
  slack:
    secure: RVF9kM2YPIpJgLk33frHD82KhC7Vl8gXytlARpwpYwtsPJXZQngYHpdWk4rEZIP7MiSj0fFxO6icY8S2eWXRftyf8rWZVY4hENHt6afyE+mYuVnEdvjDaprS/2sBUlU+lz//23mtME0jR2EC+TuJYL4f8LaZ4+2UGSDlUZKu4Q00YhNUubfc2sTkLWfRaSzHMcsl2iZs4H7JzOOLr4+mUEl1Ybzv+3LtqQ2ePODDsdytBcT6o7ILAX0PZz6495lhAVus2G4NNSDGYax4rFSjviLOpFGLQLQgCd30IBWj1Bll+dNCjjW1HVq+h3XHt4DQt3GeswYLLxNn5OMICc7B+Ao0uSfbU3sqRsMvK/Pfwe33YwgYJ6OzMVK35+91u8ZZcSJTqjsy7teLGmor8hqC2w821gB68JqAxDPg7+8zZBYPnqnRCoqNuu33ymY0ya1QQ08dBlnVqMQV7guB+9mad6GQmaPodhVCfVgvP4Stqtvh8yhrkLLiZ+PlE0LjmIFpXFmf3sK1zuzi0VFpZcGqXkCSrRNs8e5W/7UIYgv83iGCewXqxqTPTNpehtrb3p2n91gtQTKpMJJi2Rc3xFLP9jYetS/E1s6BB+vYbHPZzeE0oJUY2ff0zew16JL5sDQebswgwhmaVk9h7GC1DLkivUHuS/VjC+jY7Oa20xyAedE=
deploy:
  provider: heroku
  api_key:
    secure: q4s5iB92N+AT27xAioThTGu9PCQgZD2pvv9UOyZojdBV6wM1p2tgkzzxms0wjRLCuWINSfJ8gP6eK6xKhUBzi+HpD6vLnIGfxMy0zjbdALtiHCzN5+cECbd05owJ0fYXPga84qJV1rL+pzVjnPCVc6jtqp9gG0kwHXfhD2YQdlGtzHktJBSxTXbYgFYEJmbecKqkXOcAy97E/s4NwonBIzzRh+J4tWRFfO8pPKTtNrZybjcZ4ev/viGRckBDgpcJco1iHDJ9okCw79V5/LFP6kpU4PYoItBGK7zkbTZ6jqdd1ZVGmrstxXLIr7zTkr1auAa1CSSsMHuK3HP7olRtndYYuapBs8K1epB2otqxzIRPaxoJPRsxPNDQ81SDGDpbOIH1WC6j5DbpWoNaDq4hZJ1us0LIFRC4k26glBCJRXzluNW2FMis6VMSSz45DXbwGm9RWl35+MFkx84RS2NKJTkgPFBTWwD3FS0VLrvbpyigfl90EiQYBNZ0Adl5fKb0Fu7XGeSJ8NwTzdWIRiz1uW6C93J4PiIkEREOaVeu7FdKDIfar9mEU/MDDihp/sMygeFN0D3MHsCIGG6UTW4XaqU40V40s7hKlLJomk5WOTGjEmJjCsKVzciPoLNOZbt78BH+y4y4H+Coawn6LOxeiZaNWX9HUxtTDzLIVzFVD0c=
